version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Flake8
          command: |
            python3 -m pip install flake8
      - run:
          name: Run Flake8
          command: |
            python3 -m flake8 --ignore=E501

  test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: python3 -m unittest discover -s Tests -p 'test_*.py'
          name: Run tests

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
